version: '3.5'
services:
  postgres:
    image: "postgres"
    ports:
    - "5432:5432"
    volumes:
    - /srv/docker/conference:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres